In [1]:
import numpy as np
import os,sys

ROOT_DIR = os.path.abspath("../")
sys.path.append(ROOT_DIR)

from core.rlCuber import *

In [2]:
env = rlcuber()
print(env.observation_spacen())
print(env.action_spacen())

54
6


In [4]:
#Initialize table with all zeros
Q = np.zeros([env.observation_spacen(),env.action_spacen()])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    print("===== new episode =====")
    rAll = 0
    d = False
    j = 0
    shigh = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        noise = Q[s,:] + np.random.randn(1,env.action_spacen())*(1./(i+1))
        a = np.argmax(noise)
        #Get new state and reward from environment
        s1,r,d = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if s>shigh:
            shigh = s
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

0
[[ 0.43621069 -1.24967464 -0.41458456 -1.29093009  0.40302379  0.38558835]]
         [g][g][r]
         [w][y][w]
         [b][b][w]
[w][o][w][r][o][o][g][b][g][y][w][r]
[o][r][g][r][g][r][y][o][b][r][b][g]
[g][b][b][y][o][y][b][g][b][w][r][o]
         [r][y][o]
         [y][w][y]
         [y][w][o]

[[-0.45913556  0.21043213  0.90554362  1.3204153  -0.61789284  0.85715304]]
         [g][g][r]
         [w][y][w]
         [b][g][w]
[w][o][r][y][r][r][b][b][g][y][w][r]
[o][r][y][o][g][o][b][o][b][r][b][g]
[g][b][o][y][r][o][w][g][b][w][r][o]
         [b][y][g]
         [y][w][y]
         [y][w][o]

[[-2.17137107 -1.00528624 -1.19716366  1.15159839  0.4623951  -0.72561315]]
         [g][g][r]
         [w][y][w]
         [o][y][r]
[w][o][b][y][o][y][b][b][g][y][w][r]
[o][r][y][r][g][r][g][o][b][r][b][g]
[g][b][g][o][o][r][w][g][b][w][r][o]
         [w][b][b]
         [y][w][y]
         [y][w][o]

[[-0.33036953  0.81611734 -0.57985338 -0.32475499 -0.59130351  0.44814816]]
         [o][w][

[[ 0.50400323  0.37975601 -0.53240209  1.26507809 -1.68930284  0.35972982]]
         [w][y][w]
         [o][y][w]
         [r][y][g]
[g][b][g][y][o][r][w][g][r][b][b][o]
[r][r][r][b][g][y][g][o][g][o][b][w]
[w][o][r][b][g][o][y][w][o][g][r][b]
         [y][r][b]
         [w][w][b]
         [o][y][y]

[[-0.58409123 -0.56444483 -0.81542587 -0.67113661 -1.16866803  1.23138126]]
         [b][y][w]
         [w][y][w]
         [o][y][g]
[w][r][g][w][o][r][w][g][r][b][b][o]
[o][r][b][o][g][y][g][o][g][o][b][w]
[r][r][g][r][g][o][y][w][o][g][r][y]
         [y][r][b]
         [b][w][b]
         [b][y][y]

[[ 0.43931696 -0.33813466 -0.56796644  1.18900331  0.38247823  1.9431413 ]]
         [y][y][w]
         [w][y][w]
         [o][y][g]
[r][o][w][b][o][r][w][g][r][b][b][b]
[r][r][r][w][g][y][g][o][g][o][b][b]
[g][b][g][o][g][o][y][w][o][g][r][y]
         [w][r][b]
         [o][w][b]
         [r][y][y]

[[ 1.04041249  0.77400106 -0.51405458 -1.41493697  0.79847057 -0.79772577]]
         [r][g][o]


[[ 0.50694875  1.40599908  1.64166182  0.42150894 -1.10267153 -0.15317629]]
         [g][b][w]
         [y][y][y]
         [g][r][y]
[r][b][w][o][y][o][b][g][g][r][o][y]
[b][r][o][w][g][g][w][o][y][o][b][w]
[o][b][r][b][g][w][b][r][o][b][w][y]
         [y][o][r]
         [r][w][g]
         [g][r][w]

[[-1.03993332 -0.07625842  0.99769125  1.26759062 -1.1009469   0.76084258]]
         [g][b][w]
         [y][y][y]
         [r][o][w]
[r][b][y][b][w][o][g][g][g][r][o][y]
[b][r][o][g][g][y][r][o][y][o][b][w]
[o][b][r][w][g][o][y][r][o][b][w][y]
         [b][w][b]
         [r][w][g]
         [g][r][w]

[[-0.55530039  0.96090582  0.29954296 -1.72975487  1.45374693 -0.64929907]]
         [g][b][w]
         [y][y][y]
         [r][o][w]
[r][b][y][b][w][o][g][g][g][r][o][y]
[b][r][o][g][g][y][r][o][y][o][b][w]
[b][w][y][o][b][r][w][g][o][y][r][o]
         [g][r][b]
         [r][w][w]
         [w][g][b]

[[-1.43895356 -1.52536304  0.51720291  0.63282503  0.17641074 -1.41508699]]
         [g][b][w


[[ 0.10746428  0.60845305 -0.01047183  0.22758024  1.06744781 -0.3649404 ]]
         [g][y][g]
         [b][y][g]
         [y][y][b]
[w][o][b][r][g][y][o][o][o][y][o][r]
[w][r][o][w][g][w][g][o][r][y][b][b]
[w][r][r][w][r][g][o][b][y][g][b][b]
         [b][g][w]
         [w][w][y]
         [o][r][r]

[[-0.04209449  0.96667335  0.21773927  0.65234844  0.13249683  0.76565018]]
         [y][b][g]
         [y][y][y]
         [b][g][g]
[r][g][y][o][o][o][y][o][r][w][o][b]
[w][r][o][w][g][w][g][o][r][y][b][b]
[w][r][r][w][r][g][o][b][y][g][b][b]
         [b][g][w]
         [w][w][y]
         [o][r][r]

[[0.2232944  0.96393855 0.20820045 0.04025318 0.00978615 0.28726862]]
         [b][y][y]
         [g][y][b]
         [g][y][g]
[o][o][o][y][o][r][w][o][b][r][g][y]
[w][r][o][w][g][w][g][o][r][y][b][b]
[w][r][r][w][r][g][o][b][y][g][b][b]
         [b][g][w]
         [w][w][y]
         [o][r][r]

[[ 0.10737571 -0.39866532  1.07180532 -0.24052868 -0.37669877 -0.90211822]]
         [b][y][r]
    

         [w][w][b]
         [y][y][r]
         [y][o][y]
[g][o][r][g][b][b][r][w][y][o][o][o]
[y][r][r][b][g][y][g][o][g][o][b][r]
[w][w][b][r][r][y][o][w][w][r][b][b]
         [w][g][g]
         [b][w][g]
         [o][y][g]

[[ 0.1593216   0.62810473 -0.46740801 -0.08420118  0.19899235 -0.28810412]]
         [y][y][w]
         [o][y][w]
         [y][r][b]
[g][b][b][r][w][y][o][o][o][g][o][r]
[y][r][r][b][g][y][g][o][g][o][b][r]
[w][w][b][r][r][y][o][w][w][r][b][b]
         [w][g][g]
         [b][w][g]
         [o][y][g]

[[ 0.02593918  0.5410381  -0.14970259 -0.74941988 -0.16962207  0.50638804]]
         [y][o][y]
         [r][y][y]
         [b][w][w]
[r][w][y][o][o][o][g][o][r][g][b][b]
[y][r][r][b][g][y][g][o][g][o][b][r]
[w][w][b][r][r][y][o][w][w][r][b][b]
         [w][g][g]
         [b][w][g]
         [o][y][g]

[[-0.6090762  -0.34444132 -0.18482367  0.2203392  -0.29902848  0.56314969]]
         [b][o][y]
         [r][y][y]
         [b][w][w]
[w][y][r][y][o][o][g][o][r][g][b][o]


         [w][w][w]
         [b][y][w]
         [w][g][b]
[g][r][r][b][y][y][o][o][b][o][r][o]
[g][r][g][w][g][b][w][o][o][b][b][r]
[y][r][r][y][y][r][g][y][o][g][g][b]
         [g][o][w]
         [y][w][b]
         [r][o][y]

0
[[ 0.26551385 -0.22489652 -0.01928243 -0.87393487 -0.18786005 -0.48295179]]
         [b][w][y]
         [o][y][o]
         [r][o][b]
[r][b][y][b][w][o][w][g][g][o][r][w]
[b][r][g][r][g][r][y][o][b][r][b][w]
[g][y][g][r][w][o][y][y][o][w][y][r]
         [y][g][b]
         [o][w][g]
         [w][b][g]

[[-0.1023091   0.16600028  0.29296292 -0.65250276 -0.50932861 -0.21181675]]
         [b][w][o]
         [o][y][r]
         [r][o][o]
[r][b][y][b][w][b][y][y][w][b][r][w]
[b][r][g][r][g][g][y][o][g][o][b][w]
[g][y][g][r][w][g][o][b][g][y][y][r]
         [y][g][w]
         [o][w][r]
         [w][b][o]

[[-0.24396408 -0.48931299 -0.39176774 -0.63987027  0.39902516 -0.19690707]]
         [b][w][o]
         [o][y][r]
         [r][o][o]
[r][b][y][b][w][b][y][y][w][b][r][w

         [y][o][b]
         [r][y][b]
         [y][g][o]
[g][y][b][r][r][b][y][w][w][r][g][r]
[w][r][b][o][g][w][r][o][y][g][b][o]
[r][g][o][w][y][o][b][o][o][g][b][w]
         [g][b][w]
         [w][w][y]
         [g][r][y]

[[ 0.12253086 -0.00553657 -0.15878926  0.25196435 -0.7330646  -0.2734466 ]]
         [y][o][b]
         [r][y][b]
         [o][b][b]
[g][y][g][w][o][r][y][w][w][r][g][r]
[w][r][b][y][g][r][g][o][y][g][b][o]
[r][g][w][o][w][b][o][o][o][g][b][w]
         [b][r][y]
         [w][w][y]
         [g][r][y]

[[-0.06757522 -0.00554759 -0.36926178  0.29848902  0.38892753  0.08317324]]
         [y][o][b]
         [r][y][b]
         [o][b][b]
[g][y][g][w][o][r][y][w][w][r][g][r]
[w][r][b][y][g][r][g][o][y][g][b][o]
[g][b][w][r][g][w][o][w][b][o][o][o]
         [g][w][b]
         [r][w][r]
         [y][y][y]

[[ 1.52645393e-01  2.81874912e-03 -1.34808579e-01 -1.38258518e-01
   1.64119979e-01 -1.53007473e-04]]
         [y][o][b]
         [r][y][b]
         [o][b][b]
[g][y][g][w


[[ 0.0032846   0.13652927 -0.07147545 -0.79668638  0.58990846 -0.39682866]]
         [g][g][o]
         [w][y][w]
         [g][b][g]
[y][o][r][w][r][y][r][g][g][w][r][o]
[o][r][o][g][g][w][b][o][r][w][b][y]
[w][y][b][y][g][b][r][b][b][o][b][b]
         [r][y][w]
         [r][w][y]
         [o][o][y]

[[-0.30382927  0.55985344  0.091761    0.06382595 -0.55851502 -0.31927034]]
         [g][w][g]
         [b][y][g]
         [g][w][o]
[w][r][y][r][g][g][w][r][o][y][o][r]
[o][r][o][g][g][w][b][o][r][w][b][y]
[w][y][b][y][g][b][r][b][b][o][b][b]
         [r][y][w]
         [r][w][y]
         [o][o][y]

[[-0.41843395  0.22776623 -0.0461422  -0.38983187  0.29054633 -0.32404268]]
         [g][w][g]
         [b][y][g]
         [g][w][o]
[w][r][y][r][g][g][w][r][o][y][o][r]
[o][r][o][g][g][w][b][o][r][w][b][y]
[o][b][b][w][y][b][y][g][b][r][b][b]
         [o][r][r]
         [o][w][y]
         [y][y][w]

[[-0.18601215 -0.5242249  -0.19673921  0.25223976 -0.41786667 -0.52367232]]
         [g][w][g

KeyboardInterrupt: 